# Generated by Django 2.2.6 on 2019-10-11 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='path',
            unique_together={('domain', 'redirect_from')},
        ),
    ]
