# Generated by Django 2.2.6 on 2019-10-18 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_path_default_redirect_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='path',
            name='default_redirect_to',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
